FROM composer:latest AS composer

WORKDIR /build/composer

COPY ./ /build/composer/

RUN rm -r ./javascript

RUN composer install

FROM php:8.4-fpm-alpine

WORKDIR /var/www/html

# RUN apk update && apk upgrade
# apk add --no-cache \
# php php-fpm php-session php-mbstring php-json php-curl php-ctype \
# php-tokenizer php-phar php-xml php-zip php-opcache php-fileinfo \
# php-pdo_sqlite

COPY --from=composer /build/composer /var/www/html

# CMD ["sh", "-c", "php-fpm8 -F & nginx -g 'daemon off;'"]