FROM node:latest AS npm

WORKDIR /build/npm

COPY ./javascript/ /build/npm/

RUN npm install

RUN npm run build

FROM nginx:alpine AS nginx 

COPY ./public_html /var/www/html/public_html

COPY --from=npm /build/npm/dist /var/www/html/public_html/dist